apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterversions.tenancy.x-k8s.io
spec:
  group: tenancy.x-k8s.io
  names:
    kind: ClusterVersion
    plural: clusterversions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiServer:
              properties:
                metadata:
                  type: object
                options:
                  items:
                    properties:
                      defaultValue:
                        type: string
                      description:
                        type: string
                      metadata:
                        type: object
                      required:
                        type: boolean
                    required:
                    - required
                    type: object
                  type: array
                service:
                  type: object
                statefulset:
                  type: object
              type: object
            controllerManager:
              properties:
                metadata:
                  type: object
                options:
                  items:
                    properties:
                      defaultValue:
                        type: string
                      description:
                        type: string
                      metadata:
                        type: object
                      required:
                        type: boolean
                    required:
                    - required
                    type: object
                  type: array
                service:
                  type: object
                statefulset:
                  type: object
              type: object
            etcd:
              properties:
                metadata:
                  type: object
                options:
                  items:
                    properties:
                      defaultValue:
                        type: string
                      description:
                        type: string
                      metadata:
                        type: object
                      required:
                        type: boolean
                    required:
                    - required
                    type: object
                  type: array
                service:
                  type: object
                statefulset:
                  type: object
              type: object
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
