/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VirtualClusterSpec defines the desired state of VirtualCluster
type VirtualClusterSpec struct {
	// ClusterDomain is the domain name of the virtual cluster
	// e.g. a pod dns will be
	// {some-pod}.{some-namespace}.svc.{ClusterDomain}
	// +optional
	ClusterDomain string `json:"clusterDomain,omitempty"`

	// The name of the desired cluster version
	ClusterVersionName string `json:"clusterVersionName"`

	// The valid period of the tenant cluster PKI, if not set
	// the PKI will never expire (i.e. 10 years)
	// +optional
	PKIExpireDays int64 `json:"pkiExpireDays,omitempty"`

	// The key prefix of labels or annotations that should be back populated to Virtual Cluster.
	// These meta data are generated by super master controllers, which are needed by
	// virtual cluster to interact with external systems.
	// +optional
	TransparentMetaPrefixes []string `json:"transparentMetaPrefixes,omitempty"`

	// The key prefix of labels or annotations that are not visible to Virtual Cluster but
	// are kept in super master. For example, the annotations added by syncer controller.
	// +optional
	OpaqueMetaPrefixes []string `json:"opaqueMetaPrefixes,omitempty"`

	// Service CIDRs used by VirtualCluster
	// +optional
	ServiceCidr string `json:"serviceCidr,omitempty"`
}

// VirtualClusterStatus defines the observed state of VirtualCluster
type VirtualClusterStatus struct {
	// cluster phase of the virtual cluster
	Phase ClusterPhase `json:"phase"`

	// A human readable message indicating details about why the cluster is in
	// this condition.
	// +optional
	Message string `json:"message"`

	// A brief CamelCase message indicating details about why the cluster is in
	// this state.
	// e.g. 'Evicted'
	// +optional
	Reason string `json:"reason"`

	// Cluster Conditions
	Conditions []ClusterCondition `json:"conditions,omitempty"`
}

type ClusterPhase string

const (
	// Cluster is processed by Operator, but not all components are ready
	ClusterPending ClusterPhase = "Pending"

	// All components are ready
	ClusterRunning ClusterPhase = "Running"

	// when update cluster spec, phase will be updating
	ClusterUpdating ClusterPhase = "Updating"

	// Cluster can not be initiated, or occur the error that Operator
	// can not recover
	ClusterError ClusterPhase = "Error"
)

type ClusterCondition struct {
	// Cluster Condition Status
	// Can be True, False, Unknown.
	Status corev1.ConditionStatus `json:"status"`

	// Last time the condition transitioned from one status to another.
	// +optional
	LastTransitionTime metav1.Time `json:"lastTransitionTime,omitempty"`

	// Unique, one-word, CamelCase reason for the condition's last transition.
	// +optional
	Reason string `json:"reason,omitempty"`

	// Human-readable message indicating details about last transition.
	// +optional
	Message string `json:"message,omitempty"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:resource:shortName=vc
// +k8s:openapi-gen=true

// VirtualCluster is the Schema for the virtualclusters API
// +k8s:openapi-gen=true
type VirtualCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   VirtualClusterSpec   `json:"spec,omitempty"`
	Status VirtualClusterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// VirtualClusterList contains a list of VirtualCluster
type VirtualClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VirtualCluster `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VirtualCluster{}, &VirtualClusterList{})
}
