kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team-b-admin
subjects:
- kind: Group
  name: team-b@foo-corp.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
