// Copyright 2017 The Kubernetes Authors.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "sigs.k8s.io/multi-tenancy/poc/tenant-controller/pkg/apis/tenants/v1alpha1"
)

// FakeNamespaceTemplates implements NamespaceTemplateInterface
type FakeNamespaceTemplates struct {
	Fake *FakeTenantsV1alpha1
}

var namespacetemplatesResource = schema.GroupVersionResource{Group: "tenants.k8s.io", Version: "v1alpha1", Resource: "namespacetemplates"}

var namespacetemplatesKind = schema.GroupVersionKind{Group: "tenants.k8s.io", Version: "v1alpha1", Kind: "NamespaceTemplate"}

// Get takes name of the namespaceTemplate, and returns the corresponding namespaceTemplate object, and an error if there is any.
func (c *FakeNamespaceTemplates) Get(name string, options v1.GetOptions) (result *v1alpha1.NamespaceTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(namespacetemplatesResource, name), &v1alpha1.NamespaceTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceTemplate), err
}

// List takes label and field selectors, and returns the list of NamespaceTemplates that match those selectors.
func (c *FakeNamespaceTemplates) List(opts v1.ListOptions) (result *v1alpha1.NamespaceTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(namespacetemplatesResource, namespacetemplatesKind, opts), &v1alpha1.NamespaceTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NamespaceTemplateList{ListMeta: obj.(*v1alpha1.NamespaceTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.NamespaceTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested namespaceTemplates.
func (c *FakeNamespaceTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(namespacetemplatesResource, opts))
}

// Create takes the representation of a namespaceTemplate and creates it.  Returns the server's representation of the namespaceTemplate, and an error, if there is any.
func (c *FakeNamespaceTemplates) Create(namespaceTemplate *v1alpha1.NamespaceTemplate) (result *v1alpha1.NamespaceTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(namespacetemplatesResource, namespaceTemplate), &v1alpha1.NamespaceTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceTemplate), err
}

// Update takes the representation of a namespaceTemplate and updates it. Returns the server's representation of the namespaceTemplate, and an error, if there is any.
func (c *FakeNamespaceTemplates) Update(namespaceTemplate *v1alpha1.NamespaceTemplate) (result *v1alpha1.NamespaceTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(namespacetemplatesResource, namespaceTemplate), &v1alpha1.NamespaceTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceTemplate), err
}

// Delete takes name of the namespaceTemplate and deletes it. Returns an error if one occurs.
func (c *FakeNamespaceTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(namespacetemplatesResource, name), &v1alpha1.NamespaceTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNamespaceTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(namespacetemplatesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NamespaceTemplateList{})
	return err
}

// Patch applies the patch and returns the patched namespaceTemplate.
func (c *FakeNamespaceTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NamespaceTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(namespacetemplatesResource, name, pt, data, subresources...), &v1alpha1.NamespaceTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NamespaceTemplate), err
}
