// Copyright 2017 The Kubernetes Authors.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	tenantsv1alpha1 "sigs.k8s.io/multi-tenancy/poc/tenant-controller/pkg/apis/tenants/v1alpha1"
	clientsetv1alpha1 "sigs.k8s.io/multi-tenancy/poc/tenant-controller/pkg/clients/tenants/clientset/v1alpha1"
	internalinterfaces "sigs.k8s.io/multi-tenancy/poc/tenant-controller/pkg/clients/tenants/informers/externalversions/internalinterfaces"
	v1alpha1 "sigs.k8s.io/multi-tenancy/poc/tenant-controller/pkg/clients/tenants/listers/tenants/v1alpha1"
)

// NamespaceTemplateInformer provides access to a shared informer and lister for
// NamespaceTemplates.
type NamespaceTemplateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NamespaceTemplateLister
}

type namespaceTemplateInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewNamespaceTemplateInformer constructs a new informer for NamespaceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNamespaceTemplateInformer(client clientsetv1alpha1.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNamespaceTemplateInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredNamespaceTemplateInformer constructs a new informer for NamespaceTemplate type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNamespaceTemplateInformer(client clientsetv1alpha1.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenantsV1alpha1().NamespaceTemplates().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TenantsV1alpha1().NamespaceTemplates().Watch(options)
			},
		},
		&tenantsv1alpha1.NamespaceTemplate{},
		resyncPeriod,
		indexers,
	)
}

func (f *namespaceTemplateInformer) defaultInformer(client clientsetv1alpha1.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNamespaceTemplateInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *namespaceTemplateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tenantsv1alpha1.NamespaceTemplate{}, f.defaultInformer)
}

func (f *namespaceTemplateInformer) Lister() v1alpha1.NamespaceTemplateLister {
	return v1alpha1.NewNamespaceTemplateLister(f.Informer().GetIndexer())
}
