kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sres-admin
subjects:
- kind: Group
  name: sre@foo-corp.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
