#!/bin/bash

set -o errexit
set -o errtrace
set -o nounset

clustername=$1

# delete all secrets
kubectl delete secret -n $clustername $(kubectl get secret -n $clustername | awk 'NR>1 {print $1}') 

# delete the namespace
kubectl delete ns $clustername 

# delete the virtual cluster
kubectl delete virtualcluster $clustername
