apiVersion: hnc.x-k8s.io/v1alpha1
kind: HNCConfiguration
metadata:
  name: config
spec:
  types:
    - apiVersion: v1
      kind: Secret
      mode: ignore
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      mode: propagate
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      mode: propagate
