# permissions for end users to view tenantnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantnamespace-viewer-role
rules:
- apiGroups:
  - tenancy.x-k8s.io
  resources:
  - tenantnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenancy.x-k8s.io
  resources:
  - tenantnamespaces/status
  verbs:
  - get
