steps:
# Build release container image
- name: gcr.io/cloud-builders/git      # pull source
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git clone https://github.com/kubernetes-sigs/multi-tenancy
    cd multi-tenancy
    git checkout hnc-$_HNC_IMG_TAG
- name: gcr.io/cloud-builders/docker   # build docker image
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hnc/controller:$_HNC_IMG_TAG', 'multi-tenancy/incubator/hnc']
- name: mirror.gcr.io/library/golang   # build kubectl plugin
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd multi-tenancy/incubator/hnc
    mkdir bin
    mkdir manifests
    touch manifests/kustomization.yaml
    go build -o bin/kubectl-hierarchical_namespaces ./cmd/kubectl/main.go
- name: gcr.io/cloud-builders/curl     # upload kubectl plugin
  args:
  - '-X'
  - 'POST'
  - '-H'
  - 'Content-Type: application/x-application'
  - '--data-binary'
  - '@multi-tenancy/incubator/hnc/bin/kubectl-hierarchical_namespaces'
  - '-u'
  - '$_HNC_USER:$_HNC_PERSONAL_ACCESS_TOKEN'
  - 'https://uploads.github.com/repos/kubernetes-sigs/multi-tenancy/releases/$_HNC_RELEASE_ID/assets?name=kubectl-hierarchical_namespaces'

images: ['gcr.io/$PROJECT_ID/hnc/controller:$_HNC_IMG_TAG']
